[default.extend-words]
"sanitized" = "sanitized"
"organization" = "organization"
"Math" = "Math"
"Initializes" = "Initializes"
"utilize" = "utilize"
"labeled" = "labeled"
"Initialized" = "Initialized"
"initialize" = "initialize"
"authorize" = "authorize"
"color" = "color"
"colors" = "colors"
"colorize" = "colorize"
"Colored" = "Colored"
"Authorization" = "Authorization"
"Artifact" = "Artifact"
